import type { Occasion, Outfit } from '@ggai/shared/types'

export const seedOccasions: Occasion[] = [
  { id: 'work-commute', name: '上班通勤', icon: '🏢', description: '适合日常办公室通勤穿搭' },
  { id: 'client-meeting', name: '客户会议', icon: '🤝', description: '重要客户会面的专业穿搭' },
  { id: 'weekend-date', name: '周末约会', icon: '💕', description: '轻松愉快的周末约会穿搭' },
  { id: 'girls-gathering', name: '闺蜜聚会', icon: '👯', description: '和闺蜜一起的时尚聚会穿搭' },
]

const outfitItems: Record<string, Outfit['items']> = {
  'work-commute-1': [
    { name: '垂感阔腿西装裤', brand: 'ANGEL CHEN', price: 299, category: 'bottom', image: '/assets/outfits/work-commute-1-item1.svg' },
    { name: '真丝衬衫', brand: 'ZARA', price: 199, category: 'top', image: '/assets/outfits/work-commute-1-item2.svg' },
    { name: '小方头乐福鞋', brand: 'Charles & Keith', price: 269, category: 'shoes', image: '/assets/outfits/work-commute-1-item3.svg' },
  ],
  'work-commute-2': [
    { name: '羊毛混纺西装外套', brand: 'MASSIMO DUTTI', price: 599, category: 'outerwear', image: '/assets/outfits/work-commute-2-item1.svg' },
    { name: '高领针织衫', brand: 'UNIQLO', price: 149, category: 'top', image: '/assets/outfits/work-commute-2-item2.svg' },
    { name: '直筒西裤', brand: 'COS', price: 399, category: 'bottom', image: '/assets/outfits/work-commute-2-item3.svg' },
  ],
  'work-commute-3': [
    { name: '条纹衬衫连衣裙', brand: '& Other Stories', price: 449, category: 'dress', image: '/assets/outfits/work-commute-3-item1.svg' },
    { name: '尖头低跟鞋', brand: 'Sam Edelman', price: 359, category: 'shoes', image: '/assets/outfits/work-commute-3-item2.svg' },
  ],
  'work-commute-4': [
    { name: '宽松针织开衫', brand: 'Everlane', price: 329, category: 'outerwear', image: '/assets/outfits/work-commute-4-item1.svg' },
    { name: '烟管裤', brand: 'JNBY', price: 269, category: 'bottom', image: '/assets/outfits/work-commute-4-item2.svg' },
    { name: '基础棉T恤', brand: 'UNIQLO', price: 79, category: 'top', image: '/assets/outfits/work-commute-4-item3.svg' },
  ],
  'client-meeting-1': [
    { name: '双排扣西装套装', brand: 'Theory', price: 1299, category: 'outerwear', image: '/assets/outfits/client-meeting-1-item1.svg' },
    { name: '丝质衬衫', brand: 'Equipment', price: 699, category: 'top', image: '/assets/outfits/client-meeting-1-item2.svg' },
    { name: '尖头高跟鞋', brand: 'Stuart Weitzman', price: 899, category: 'shoes', image: '/assets/outfits/client-meeting-1-item3.svg' },
  ],
  'client-meeting-2': [
    { name: '真丝衬衫裙', brand: 'Vince', price: 899, category: 'dress', image: '/assets/outfits/client-meeting-2-item1.svg' },
    { name: '细腰带', brand: 'Mango', price: 129, category: 'accessory', image: '/assets/outfits/client-meeting-2-item2.svg' },
    { name: '简约链条包', brand: 'Polène', price: 799, category: 'accessory', image: '/assets/outfits/client-meeting-2-item3.svg' },
  ],
  'client-meeting-3': [
    { name: '立领衬衫', brand: 'COS', price: 349, category: 'top', image: '/assets/outfits/client-meeting-3-item1.svg' },
    { name: '九分西裤', brand: 'Maje', price: 599, category: 'bottom', image: '/assets/outfits/client-meeting-3-item2.svg' },
    { name: '乐福鞋', brand: 'Tod\'s', price: 1099, category: 'shoes', image: '/assets/outfits/client-meeting-3-item3.svg' },
  ],
  'weekend-date-1': [
    { name: '碎花连衣裙', brand: 'Réalisation Par', price: 529, category: 'dress', image: '/assets/outfits/weekend-date-1-item1.svg' },
    { name: '编织手袋', brand: 'Cult Gaia', price: 449, category: 'accessory', image: '/assets/outfits/weekend-date-1-item2.svg' },
    { name: '细带凉鞋', brand: 'By Far', price: 649, category: 'shoes', image: '/assets/outfits/weekend-date-1-item3.svg' },
  ],
  'weekend-date-2': [
    { name: '法式针织上衣', brand: 'Sézane', price: 379, category: 'top', image: '/assets/outfits/weekend-date-2-item1.svg' },
    { name: 'A字短裙', brand: 'ZARA', price: 199, category: 'bottom', image: '/assets/outfits/weekend-date-2-item2.svg' },
    { name: '玛丽珍鞋', brand: 'Carel', price: 699, category: 'shoes', image: '/assets/outfits/weekend-date-2-item3.svg' },
  ],
  'weekend-date-3': [
    { name: '蕾丝拼接上衣', brand: 'For Love & Lemons', price: 449, category: 'top', image: '/assets/outfits/weekend-date-3-item1.svg' },
    { name: '高腰牛仔裤', brand: 'Levi\'s', price: 399, category: 'bottom', image: '/assets/outfits/weekend-date-3-item2.svg' },
  ],
  'girls-gathering-1': [
    { name: '亮片吊带裙', brand: 'The Attico', price: 899, category: 'dress', image: '/assets/outfits/girls-gathering-1-item1.svg' },
    { name: '链条腋下包', brand: 'Jacquemus', price: 1299, category: 'accessory', image: '/assets/outfits/girls-gathering-1-item2.svg' },
  ],
  'girls-gathering-2': [
    { name: '廓形牛仔外套', brand: 'Acne Studios', price: 1099, category: 'outerwear', image: '/assets/outfits/girls-gathering-2-item1.svg' },
    { name: '印花T恤', brand: 'Stüssy', price: 329, category: 'top', image: '/assets/outfits/girls-gathering-2-item2.svg' },
    { name: '工装裤', brand: 'Dickies', price: 249, category: 'bottom', image: '/assets/outfits/girls-gathering-2-item3.svg' },
  ],
  'girls-gathering-3': [
    { name: '缎面吊带裙', brand: 'Ganni', price: 699, category: 'dress', image: '/assets/outfits/girls-gathering-3-item1.svg' },
    { name: '厚底马丁靴', brand: 'Dr. Martens', price: 599, category: 'shoes', image: '/assets/outfits/girls-gathering-3-item2.svg' },
  ],
}

export const seedOutfits: Outfit[] = [
  {
    id: 'work-commute-1',
    occasion: 'work-commute',
    name: '知性通勤套装',
    items: outfitItems['work-commute-1'],
    totalPrice: 767,
    priceRange: 'mid',
    styleTags: ['简约通勤', '优雅知性'],
    coverImage: '/assets/outfits/work-commute-1-main.svg',
    brandSummary: 'ANGEL CHEN + ZARA + Charles & Keith',
  },
  {
    id: 'work-commute-2',
    occasion: 'work-commute',
    name: '优雅西装look',
    items: outfitItems['work-commute-2'],
    totalPrice: 1147,
    priceRange: 'premium',
    styleTags: ['简约通勤', '职业精英'],
    coverImage: '/assets/outfits/work-commute-2-main.svg',
    brandSummary: 'MASSIMO DUTTI + UNIQLO + COS',
  },
  {
    id: 'work-commute-3',
    occasion: 'work-commute',
    name: '清爽衬衫裙',
    items: outfitItems['work-commute-3'],
    totalPrice: 808,
    priceRange: 'mid',
    styleTags: ['简约通勤', '温柔甜美'],
    coverImage: '/assets/outfits/work-commute-3-main.svg',
    brandSummary: '& Other Stories + Sam Edelman',
  },
  {
    id: 'work-commute-4',
    occasion: 'work-commute',
    name: '轻松休闲办公',
    items: outfitItems['work-commute-4'],
    totalPrice: 677,
    priceRange: 'mid',
    styleTags: ['简约通勤', '休闲舒适'],
    coverImage: '/assets/outfits/work-commute-4-main.svg',
    brandSummary: 'Everlane + JNBY + UNIQLO',
  },
  {
    id: 'client-meeting-1',
    occasion: 'client-meeting',
    name: '气场西装套装',
    items: outfitItems['client-meeting-1'],
    totalPrice: 2897,
    priceRange: 'luxury',
    styleTags: ['职业精英', '优雅知性'],
    coverImage: '/assets/outfits/client-meeting-1-main.svg',
    brandSummary: 'Theory + Equipment + Stuart Weitzman',
  },
  {
    id: 'client-meeting-2',
    occasion: 'client-meeting',
    name: '高级感连衣裙',
    items: outfitItems['client-meeting-2'],
    totalPrice: 1827,
    priceRange: 'luxury',
    styleTags: ['优雅知性', '简约通勤'],
    coverImage: '/assets/outfits/client-meeting-2-main.svg',
    brandSummary: 'Vince + Mango + Polène',
  },
  {
    id: 'client-meeting-3',
    occasion: 'client-meeting',
    name: '干练知性风',
    items: outfitItems['client-meeting-3'],
    totalPrice: 2047,
    priceRange: 'premium',
    styleTags: ['简约通勤', '职业精英'],
    coverImage: '/assets/outfits/client-meeting-3-main.svg',
    brandSummary: 'COS + Maje + Tod\'s',
  },
  {
    id: 'weekend-date-1',
    occasion: 'weekend-date',
    name: '碎花浪漫约会',
    items: outfitItems['weekend-date-1'],
    totalPrice: 1627,
    priceRange: 'premium',
    styleTags: ['温柔甜美', '潮流街头'],
    coverImage: '/assets/outfits/weekend-date-1-main.svg',
    brandSummary: 'Réalisation Par + Cult Gaia + By Far',
  },
  {
    id: 'weekend-date-2',
    occasion: 'weekend-date',
    name: '法式少女风',
    items: outfitItems['weekend-date-2'],
    totalPrice: 1277,
    priceRange: 'premium',
    styleTags: ['温柔甜美', '优雅知性'],
    coverImage: '/assets/outfits/weekend-date-2-main.svg',
    brandSummary: 'Sézane + ZARA + Carel',
  },
  {
    id: 'weekend-date-3',
    occasion: 'weekend-date',
    name: '甜酷休闲约会',
    items: outfitItems['weekend-date-3'],
    totalPrice: 848,
    priceRange: 'mid',
    styleTags: ['潮流街头', '温柔甜美'],
    coverImage: '/assets/outfits/weekend-date-3-main.svg',
    brandSummary: 'For Love & Lemons + Levi\'s',
  },
  {
    id: 'girls-gathering-1',
    occasion: 'girls-gathering',
    name: '派对亮片裙',
    items: outfitItems['girls-gathering-1'],
    totalPrice: 2198,
    priceRange: 'luxury',
    styleTags: ['潮流街头', '温柔甜美'],
    coverImage: '/assets/outfits/girls-gathering-1-main.svg',
    brandSummary: 'The Attico + Jacquemus',
  },
  {
    id: 'girls-gathering-2',
    occasion: 'girls-gathering',
    name: '街头酷女孩',
    items: outfitItems['girls-gathering-2'],
    totalPrice: 1677,
    priceRange: 'premium',
    styleTags: ['潮流街头', '休闲舒适'],
    coverImage: '/assets/outfits/girls-gathering-2-main.svg',
    brandSummary: 'Acne Studios + Stüssy + Dickies',
  },
  {
    id: 'girls-gathering-3',
    occasion: 'girls-gathering',
    name: '甜酷缎面look',
    items: outfitItems['girls-gathering-3'],
    totalPrice: 1298,
    priceRange: 'premium',
    styleTags: ['温柔甜美', '潮流街头'],
    coverImage: '/assets/outfits/girls-gathering-3-main.svg',
    brandSummary: 'Ganni + Dr. Martens',
  },
]
