import type { Occasion, Outfit } from '@ggai/shared/types'
import { outfitImages } from '../assets/images'

export const seedOccasions: Occasion[] = [
  { id: 'work-commute', name: '上班通勤', icon: '🏢', description: '适合日常办公室通勤穿搭' },
  { id: 'client-meeting', name: '客户会议', icon: '🤝', description: '重要客户会面的专业穿搭' },
  { id: 'weekend-date', name: '周末约会', icon: '💕', description: '轻松愉快的周末约会穿搭' },
  { id: 'girls-gathering', name: '闺蜜聚会', icon: '👯', description: '和闺蜜一起的时尚聚会穿搭' },
]

const outfitItems: Record<string, Outfit['items']> = {
  'work-commute-1': [
    { name: '垂感阔腿西装裤', brand: 'ANGEL CHEN', price: 299, category: 'bottom', image: '/assets/outfits/work-commute-1-item1.svg' },
    { name: '真丝衬衫', brand: 'ZARA', price: 199, category: 'top', image: '/assets/outfits/work-commute-1-item2.svg' },
    { name: '小方头乐福鞋', brand: 'Charles & Keith', price: 269, category: 'shoes', image: '/assets/outfits/work-commute-1-item3.svg' },
  ],
  'work-commute-2': [
    { name: '羊毛混纺西装外套', brand: 'MASSIMO DUTTI', price: 599, category: 'outerwear', image: '/assets/outfits/work-commute-2-item1.svg' },
    { name: '高领针织衫', brand: 'UNIQLO', price: 149, category: 'top', image: '/assets/outfits/work-commute-2-item2.svg' },
    { name: '直筒西裤', brand: 'COS', price: 399, category: 'bottom', image: '/assets/outfits/work-commute-2-item3.svg' },
  ],
  'work-commute-3': [
    { name: '条纹衬衫连衣裙', brand: '& Other Stories', price: 449, category: 'dress', image: '/assets/outfits/work-commute-3-item1.svg' },
    { name: '尖头低跟鞋', brand: 'Sam Edelman', price: 359, category: 'shoes', image: '/assets/outfits/work-commute-3-item2.svg' },
  ],
  'work-commute-4': [
    { name: '宽松针织开衫', brand: 'Everlane', price: 329, category: 'outerwear', image: '/assets/outfits/work-commute-4-item1.svg' },
    { name: '烟管裤', brand: 'JNBY', price: 269, category: 'bottom', image: '/assets/outfits/work-commute-4-item2.svg' },
    { name: '基础棉T恤', brand: 'UNIQLO', price: 79, category: 'top', image: '/assets/outfits/work-commute-4-item3.svg' },
  ],
  'client-meeting-1': [
    { name: '双排扣西装套装', brand: 'Theory', price: 1299, category: 'outerwear', image: '/assets/outfits/client-meeting-1-item1.svg' },
    { name: '丝质衬衫', brand: 'Equipment', price: 699, category: 'top', image: '/assets/outfits/client-meeting-1-item2.svg' },
    { name: '尖头高跟鞋', brand: 'Stuart Weitzman', price: 899, category: 'shoes', image: '/assets/outfits/client-meeting-1-item3.svg' },
  ],
  'client-meeting-2': [
    { name: '真丝衬衫裙', brand: 'Vince', price: 899, category: 'dress', image: '/assets/outfits/client-meeting-2-item1.svg' },
    { name: '细腰带', brand: 'Mango', price: 129, category: 'accessory', image: '/assets/outfits/client-meeting-2-item2.svg' },
    { name: '简约链条包', brand: 'Polène', price: 799, category: 'accessory', image: '/assets/outfits/client-meeting-2-item3.svg' },
  ],
  'client-meeting-3': [
    { name: '立领衬衫', brand: 'COS', price: 349, category: 'top', image: '/assets/outfits/client-meeting-3-item1.svg' },
    { name: '九分西裤', brand: 'Maje', price: 599, category: 'bottom', image: '/assets/outfits/client-meeting-3-item2.svg' },
    { name: '乐福鞋', brand: 'Tod\'s', price: 1099, category: 'shoes', image: '/assets/outfits/client-meeting-3-item3.svg' },
  ],
  'weekend-date-1': [
    { name: '碎花连衣裙', brand: 'Réalisation Par', price: 529, category: 'dress', image: '/assets/outfits/weekend-date-1-item1.svg' },
    { name: '编织手袋', brand: 'Cult Gaia', price: 449, category: 'accessory', image: '/assets/outfits/weekend-date-1-item2.svg' },
    { name: '细带凉鞋', brand: 'By Far', price: 649, category: 'shoes', image: '/assets/outfits/weekend-date-1-item3.svg' },
  ],
  'weekend-date-2': [
    { name: '法式针织上衣', brand: 'Sézane', price: 379, category: 'top', image: '/assets/outfits/weekend-date-2-item1.svg' },
    { name: 'A字短裙', brand: 'ZARA', price: 199, category: 'bottom', image: '/assets/outfits/weekend-date-2-item2.svg' },
    { name: '玛丽珍鞋', brand: 'Carel', price: 699, category: 'shoes', image: '/assets/outfits/weekend-date-2-item3.svg' },
  ],
  'weekend-date-3': [
    { name: '蕾丝拼接上衣', brand: 'For Love & Lemons', price: 449, category: 'top', image: '/assets/outfits/weekend-date-3-item1.svg' },
    { name: '高腰牛仔裤', brand: 'Levi\'s', price: 399, category: 'bottom', image: '/assets/outfits/weekend-date-3-item2.svg' },
  ],
  'girls-gathering-1': [
    { name: '亮片吊带裙', brand: 'The Attico', price: 899, category: 'dress', image: '/assets/outfits/girls-gathering-1-item1.svg' },
    { name: '链条腋下包', brand: 'Jacquemus', price: 1299, category: 'accessory', image: '/assets/outfits/girls-gathering-1-item2.svg' },
  ],
  'girls-gathering-2': [
    { name: '廓形牛仔外套', brand: 'Acne Studios', price: 1099, category: 'outerwear', image: '/assets/outfits/girls-gathering-2-item1.svg' },
    { name: '印花T恤', brand: 'Stüssy', price: 329, category: 'top', image: '/assets/outfits/girls-gathering-2-item2.svg' },
    { name: '工装裤', brand: 'Dickies', price: 249, category: 'bottom', image: '/assets/outfits/girls-gathering-2-item3.svg' },
  ],
  'girls-gathering-3': [
    { name: '缎面吊带裙', brand: 'Ganni', price: 699, category: 'dress', image: '/assets/outfits/girls-gathering-3-item1.svg' },
    { name: '厚底马丁靴', brand: 'Dr. Martens', price: 599, category: 'shoes', image: '/assets/outfits/girls-gathering-3-item2.svg' },
  ],
  // New outfits
  'work-commute-5': [
    { name: '米色风衣', brand: 'Burberry', price: 1299, category: 'outerwear', image: '/assets/outfits/work-commute-5-item1.svg' },
    { name: '白色衬衫', brand: 'Everlane', price: 349, category: 'top', image: '/assets/outfits/work-commute-5-item2.svg' },
    { name: '直筒长裤', brand: 'JNBY', price: 399, category: 'bottom', image: '/assets/outfits/work-commute-5-item3.svg' },
  ],
  'client-meeting-4': [
    { name: '格纹西装套装', brand: 'Burberry', price: 2499, category: 'outerwear', image: '/assets/outfits/client-meeting-4-item1.svg' },
    { name: '真丝衬衫', brand: 'Totême', price: 899, category: 'top', image: '/assets/outfits/client-meeting-4-item2.svg' },
    { name: '鳄鱼纹手袋', brand: 'YSL', price: 1899, category: 'accessory', image: '/assets/outfits/client-meeting-4-item3.svg' },
  ],
  'weekend-date-4': [
    { name: '针织两件套', brand: 'GANNI', price: 899, category: 'top', image: '/assets/outfits/weekend-date-4-item1.svg' },
    { name: '百褶裙', brand: 'Maje', price: 599, category: 'bottom', image: '/assets/outfits/weekend-date-4-item2.svg' },
    { name: '草编包', brand: 'Loewe', price: 1599, category: 'accessory', image: '/assets/outfits/weekend-date-4-item3.svg' },
  ],
  'weekend-date-5': [
    { name: '印花衬衫', brand: 'Rixo', price: 699, category: 'top', image: '/assets/outfits/weekend-date-5-item1.svg' },
    { name: '白色牛仔裤', brand: 'Levi\'s', price: 449, category: 'bottom', image: '/assets/outfits/weekend-date-5-item2.svg' },
    { name: '藤编穆勒鞋', brand: 'Castaner', price: 529, category: 'shoes', image: '/assets/outfits/weekend-date-5-item3.svg' },
  ],
  'girls-gathering-4': [
    { name: '廓形西装外套', brand: 'Balenciaga', price: 1899, category: 'outerwear', image: '/assets/outfits/girls-gathering-4-item1.svg' },
    { name: '短上衣', brand: 'Urban Outfitters', price: 199, category: 'top', image: '/assets/outfits/girls-gathering-4-item2.svg' },
    { name: '高腰阔腿裤', brand: 'COS', price: 499, category: 'bottom', image: '/assets/outfits/girls-gathering-4-item3.svg' },
  ],
  'girls-gathering-5': [
    { name: '蕾丝连衣裙', brand: 'Self-Portrait', price: 1299, category: 'dress', image: '/assets/outfits/girls-gathering-5-item1.svg' },
    { name: '水钻高跟鞋', brand: 'Jimmy Choo', price: 2199, category: 'shoes', image: '/assets/outfits/girls-gathering-5-item2.svg' },
    { name: '珍珠手袋', brand: 'Shrimps', price: 899, category: 'accessory', image: '/assets/outfits/girls-gathering-5-item3.svg' },
  ],
  'work-commute-6': [
    { name: '羊绒混纺大衣', brand: 'Max Mara', price: 2199, category: 'outerwear', image: '/assets/outfits/work-commute-6-item1.svg' },
    { name: '真丝衬衫', brand: 'Theory', price: 599, category: 'top', image: '/assets/outfits/work-commute-6-item2.svg' },
    { name: '铅笔裤', brand: 'Uniqlo', price: 249, category: 'bottom', image: '/assets/outfits/work-commute-6-item3.svg' },
  ],
  'client-meeting-5': [
    { name: '双面羊毛大衣', brand: 'The Row', price: 3299, category: 'outerwear', image: '/assets/outfits/client-meeting-5-item1.svg' },
    { name: '高领针织衫', brand: 'Brunello Cucinelli', price: 1599, category: 'top', image: '/assets/outfits/client-meeting-5-item2.svg' },
    { name: '西裤', brand: 'Prada', price: 1299, category: 'bottom', image: '/assets/outfits/client-meeting-5-item3.svg' },
  ],
  'weekend-date-6': [
    { name: '波西米亚长裙', brand: 'Isabel Marant', price: 1299, category: 'dress', image: '/assets/outfits/weekend-date-6-item1.svg' },
    { name: '麂皮短靴', brand: 'Chloé', price: 1599, category: 'shoes', image: '/assets/outfits/weekend-date-6-item2.svg' },
    { name: '流苏斜挎包', brand: 'Chloé', price: 1899, category: 'accessory', image: '/assets/outfits/weekend-date-6-item3.svg' },
  ],
}

export const seedOutfits: Outfit[] = [
  {
    id: 'work-commute-1',
    occasion: 'work-commute',
    name: '知性通勤套装',
    items: outfitItems['work-commute-1'],
    totalPrice: 767,
    priceRange: 'mid',
    styleTags: ['简约通勤', '优雅知性'],
    coverImage: outfitImages['work-commute-1-main'],
    brandSummary: 'ANGEL CHEN + ZARA + Charles & Keith',
  },
  {
    id: 'work-commute-2',
    occasion: 'work-commute',
    name: '优雅西装look',
    items: outfitItems['work-commute-2'],
    totalPrice: 1147,
    priceRange: 'premium',
    styleTags: ['简约通勤', '职业精英'],
    coverImage: outfitImages['work-commute-2-main'],
    brandSummary: 'MASSIMO DUTTI + UNIQLO + COS',
  },
  {
    id: 'work-commute-3',
    occasion: 'work-commute',
    name: '清爽衬衫裙',
    items: outfitItems['work-commute-3'],
    totalPrice: 808,
    priceRange: 'mid',
    styleTags: ['简约通勤', '温柔甜美'],
    coverImage: outfitImages['work-commute-3-main'],
    brandSummary: '& Other Stories + Sam Edelman',
  },
  {
    id: 'work-commute-4',
    occasion: 'work-commute',
    name: '轻松休闲办公',
    items: outfitItems['work-commute-4'],
    totalPrice: 677,
    priceRange: 'mid',
    styleTags: ['简约通勤', '休闲舒适'],
    coverImage: outfitImages['work-commute-4-main'],
    brandSummary: 'Everlane + JNBY + UNIQLO',
  },
  {
    id: 'client-meeting-1',
    occasion: 'client-meeting',
    name: '气场西装套装',
    items: outfitItems['client-meeting-1'],
    totalPrice: 2897,
    priceRange: 'luxury',
    styleTags: ['职业精英', '优雅知性'],
    coverImage: outfitImages['client-meeting-1-main'],
    brandSummary: 'Theory + Equipment + Stuart Weitzman',
  },
  {
    id: 'client-meeting-2',
    occasion: 'client-meeting',
    name: '高级感连衣裙',
    items: outfitItems['client-meeting-2'],
    totalPrice: 1827,
    priceRange: 'luxury',
    styleTags: ['优雅知性', '简约通勤'],
    coverImage: outfitImages['client-meeting-2-main'],
    brandSummary: 'Vince + Mango + Polène',
  },
  {
    id: 'client-meeting-3',
    occasion: 'client-meeting',
    name: '干练知性风',
    items: outfitItems['client-meeting-3'],
    totalPrice: 2047,
    priceRange: 'premium',
    styleTags: ['简约通勤', '职业精英'],
    coverImage: outfitImages['client-meeting-3-main'],
    brandSummary: 'COS + Maje + Tod\'s',
  },
  {
    id: 'weekend-date-1',
    occasion: 'weekend-date',
    name: '碎花浪漫约会',
    items: outfitItems['weekend-date-1'],
    totalPrice: 1627,
    priceRange: 'premium',
    styleTags: ['温柔甜美', '潮流街头'],
    coverImage: outfitImages['weekend-date-1-main'],
    brandSummary: 'Réalisation Par + Cult Gaia + By Far',
  },
  {
    id: 'weekend-date-2',
    occasion: 'weekend-date',
    name: '法式少女风',
    items: outfitItems['weekend-date-2'],
    totalPrice: 1277,
    priceRange: 'premium',
    styleTags: ['温柔甜美', '优雅知性'],
    coverImage: outfitImages['weekend-date-2-main'],
    brandSummary: 'Sézane + ZARA + Carel',
  },
  {
    id: 'weekend-date-3',
    occasion: 'weekend-date',
    name: '甜酷休闲约会',
    items: outfitItems['weekend-date-3'],
    totalPrice: 848,
    priceRange: 'mid',
    styleTags: ['潮流街头', '温柔甜美'],
    coverImage: outfitImages['weekend-date-3-main'],
    brandSummary: 'For Love & Lemons + Levi\'s',
  },
  {
    id: 'girls-gathering-1',
    occasion: 'girls-gathering',
    name: '派对亮片裙',
    items: outfitItems['girls-gathering-1'],
    totalPrice: 2198,
    priceRange: 'luxury',
    styleTags: ['潮流街头', '温柔甜美'],
    coverImage: outfitImages['girls-gathering-1-main'],
    brandSummary: 'The Attico + Jacquemus',
  },
  {
    id: 'girls-gathering-2',
    occasion: 'girls-gathering',
    name: '街头酷女孩',
    items: outfitItems['girls-gathering-2'],
    totalPrice: 1677,
    priceRange: 'premium',
    styleTags: ['潮流街头', '休闲舒适'],
    coverImage: outfitImages['girls-gathering-2-main'],
    brandSummary: 'Acne Studios + Stüssy + Dickies',
  },
  {
    id: 'girls-gathering-3',
    occasion: 'girls-gathering',
    name: '甜酷缎面look',
    items: outfitItems['girls-gathering-3'],
    totalPrice: 1298,
    priceRange: 'premium',
    styleTags: ['温柔甜美', '潮流街头'],
    coverImage: outfitImages['girls-gathering-3-main'],
    brandSummary: 'Ganni + Dr. Martens',
  },
  {
    id: 'work-commute-5', occasion: 'work-commute', name: '知性风衣通勤',
    items: outfitItems['work-commute-5'], totalPrice: 2047, priceRange: 'premium',
    styleTags: ['简约通勤', '优雅知性'],
    coverImage: outfitImages['work-commute-5-main'],
    brandSummary: 'Burberry + Everlane + JNBY',
  },
  {
    id: 'work-commute-6', occasion: 'work-commute', name: '高级极简通勤',
    items: outfitItems['work-commute-6'], totalPrice: 3047, priceRange: 'luxury',
    styleTags: ['简约通勤', '职业精英'],
    coverImage: outfitImages['work-commute-6-main'],
    brandSummary: 'Max Mara + Theory + Uniqlo',
  },
  {
    id: 'client-meeting-4', occasion: 'client-meeting', name: '格纹精英套装',
    items: outfitItems['client-meeting-4'], totalPrice: 5297, priceRange: 'luxury',
    styleTags: ['职业精英', '优雅知性'],
    coverImage: outfitImages['client-meeting-4-main'],
    brandSummary: 'Burberry + Totême + YSL',
  },
  {
    id: 'client-meeting-5', occasion: 'client-meeting', name: '奢华商务会面',
    items: outfitItems['client-meeting-5'], totalPrice: 6197, priceRange: 'luxury',
    styleTags: ['职业精英', '优雅知性'],
    coverImage: outfitImages['client-meeting-5-main'],
    brandSummary: 'The Row + Brunello Cucinelli + Prada',
  },
  {
    id: 'weekend-date-4', occasion: 'weekend-date', name: '春季约会针织',
    items: outfitItems['weekend-date-4'], totalPrice: 3097, priceRange: 'luxury',
    styleTags: ['温柔甜美', '优雅知性'],
    coverImage: outfitImages['weekend-date-4-main'],
    brandSummary: 'GANNI + Maje + Loewe',
  },
  {
    id: 'weekend-date-5', occasion: 'weekend-date', name: '法式田园约会',
    items: outfitItems['weekend-date-5'], totalPrice: 1677, priceRange: 'premium',
    styleTags: ['优雅知性', '温柔甜美'],
    coverImage: outfitImages['weekend-date-5-main'],
    brandSummary: 'Rixo + Levi\'s + Castaner',
  },
  {
    id: 'weekend-date-6', occasion: 'weekend-date', name: '波西米亚晚霞',
    items: outfitItems['weekend-date-6'], totalPrice: 4797, priceRange: 'luxury',
    styleTags: ['潮流街头', '优雅知性'],
    coverImage: outfitImages['weekend-date-6-main'],
    brandSummary: 'Isabel Marant + Chloé + Chloé',
  },
  {
    id: 'girls-gathering-4', occasion: 'girls-gathering', name: '酷感闺蜜派对',
    items: outfitItems['girls-gathering-4'], totalPrice: 2597, priceRange: 'luxury',
    styleTags: ['潮流街头', '休闲舒适'],
    coverImage: outfitImages['girls-gathering-4-main'],
    brandSummary: 'Balenciaga + Urban Outfitters + COS',
  },
  {
    id: 'girls-gathering-5', occasion: 'girls-gathering', name: '精致蕾丝晚宴',
    items: outfitItems['girls-gathering-5'], totalPrice: 4397, priceRange: 'luxury',
    styleTags: ['温柔甜美', '优雅知性'],
    coverImage: outfitImages['girls-gathering-5-main'],
    brandSummary: 'Self-Portrait + Jimmy Choo + Shrimps',
  },
]
